services:
  db:
    image: postgres:18.3-alpine
    container_name: project_db
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: development
    container_name: django_backend
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost/api
    depends_on:
      - backend
  redis:
    image: redis:7-alpine
    container_name: project_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
