# Generated by Django 6.0.5 on 2026-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_size_remove_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, help_text='Застаріле поле, використовуйте Seasons', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.season'),
        ),
    ]
