# Generated by Django 6.0.5 on 2026-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_enable_trigram_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
