# Generated by Django 6.0.5 on 2026-06-03 23:20

from django.db import migrations
import random


def update_skus(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    ProductVariant = apps.get_model("shop", "ProductVariant")

    def get_unique_sku(model):
        while True:
            sku = str(random.randint(10000, 99999))
            if not model.objects.filter(sku=sku).exists():
                return sku

    # Оновлюємо продукти
    for product in Product.objects.all():
        product.sku = get_unique_sku(Product)
        product.save()

    # Оновлюємо варіанти
    for variant in ProductVariant.objects.all():
        variant.sku = get_unique_sku(ProductVariant)
        variant.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_product_sku_alter_productvariant_sku.py"),
    ]

    operations = [
        migrations.RunPython(update_skus),
    ]
